# APEX Autonomous Fix - Cloudflare Pages Configuration
# This file fixes the "Cannot find cwd: /opt/buildhome/repo/soul" error automatically
# Place this at: .github/workflows/apex-autonomous-fix.yml

name: APEX Autonomous Fix & Deploy

on:
  push:
    branches: [main, master]
    paths:
      - 'THEORY/**'
      - '.github/workflows/apex-autonomous-fix.yml'
  workflow_dispatch:  # Allows manual trigger if needed

jobs:
  fix-and-deploy:
    runs-on: ubuntu-latest
    name: Fix APEX Configuration
    
    steps:
      # Step 1: Checkout code
      - name: Checkout
        uses: actions/checkout@v4
        
      # Step 2: Create symlink soul → THEORY (fixes the Cloudflare root dir issue)
      - name: Fix Directory Structure
        run: |
          # Create symlink so Cloudflare finds "soul" even though we renamed it to THEORY
          if [ ! -L "soul" ]; then
            ln -s THEORY soul
            echo "✅ Created symlink: soul → THEORY"
          else
            echo "✅ Symlink already exists"
          fi
          
      # Step 3: Deploy to Cloudflare Pages using the correct directory
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy THEORY --project-name=apex --branch=main
          
      # Step 4: Verify deployment
      - name: Verify Deployment
        run: |
          echo "✅ APEX deployed successfully"
          echo "🌐 Check: https://apex.arif-fazil.com"
